### ISSUE TITLE
not working on front camera

### ISSUE THREAD

**Issue by handhikadj** [estebanuri/face_recognition#3]
tried this on my samsung a20 on the front camera didn't work. also it has "please update" warning when initiating the camera

**Comment by KeunJuSong** [comment]
I tried this demo on Samsung Galaxy S8, the front camera worked. 
But in the front camera, it didn't show tracking face boxes. Only show in the back camera....
How can I run in the front camera with tracking face boxes??

**Comment by estebanuri** [comment]
I'm not sure because I don't have a Samsung to test it, but I've pushed a fix that I think it might correct the issue.
Can you test it now?

**Comment by KeunJuSong** [comment]
> I'm not sure because I don't have a Samsung to test it, but I've pushed a fix that I think it might correct the issue.
> Can you test it now?

I tested it, and it worked very well!! Thank U for help this issue :)
Using Samsung Galaxy S8, this fixed app works well.
