### ISSUE TITLE
Training is not saving

### ISSUE THREAD

**Issue by HugoFerreiraStack** [estebanuri/face_recognition#4]
How to make the training with the names entered saved? After closing the app, when I come back I have to do the face registration again

**Comment by estebanuri** [comment]
This is not an issue. Storing the embeedings is part of the second-stage of the problem resolution.
The application might be extended to support database storing, but there are many options to do that.
I'll extend this functionality as a future work.

**Comment by Hina55** [comment]
@estebanuri please do that sir, we really need that solution as early as possible.

**Comment by Hina55** [comment]
@estebanuri  Sir, i want to save this training in SQLite to detect for future use, as a complete application. Any guidance will be appreciated. Can you please describe briefly the procedure as well?

**Comment by ganeshchenniah** [comment]
Hi ,
Is there a update on storing to local database ?

**Comment by volam1999** [comment]
> Hi ,
> Is there a update on storing to local database ?

https://github.com/estebanuri/face_recognition/issues/2#issuecomment-667622407
